### PR TITLE
Add support for showing label/graph for CPU/RAM

### PR DESCRIPTION
**Pull request by RyanDam**
Since this indicator only show percent for CPU/RAM, which is hard to determine which is for CPU or RAM.
I also add a simple graph bar for better visualization.

screenshot from 2018-10-22 10 17 59

### CODE REVIEW

**Comment by PlugaruT** [comment]
While I agree with the labels part, I don't like the graph implementation as it doesn't show the exact value...

**Comment by RyanDam** [comment]
> While I agree with the labels part, I don't like the graph implementation as it doesn't show the exact value...
My goal is to have a quick look at the system without look at specific number (acceptable while you have percentage there if you need exact value)

p.s: My long term goal for the graph is that it will be a line graph, it's better because you can have more information about CPU history, but I have currently not finger it out how to implement yet.

**Comment by RyanDam** [comment]
Latest commit update:
- More accurate graph using custom draw widget

Known issue:
- Not change graph color when Wingpanel change background state

Next:
- Auto change graph color when Wingpanel change background state

screenshot from 2018-10-23 13 13 31

**Comment by RyanDam** [comment]
Latest commit update:
- Auto change graph color when Wingpanel background change

screenshot from 2018-10-23 15 55 37

I think everything is good now :+1:

**Comment by RyanDam** [comment]
Too many commit for today :))
Just add line graph for CPU

screenshot from 2018-10-23 17 44 12

**Comment by PlugaruT** [comment]
Thanks for your contribution. I will merge this and I will update the readme with proper screenshots of your changes. :star2:

**Pull request merged**
